python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
c_stdlib:
  - sysroot  # [linux]
  - macosx_deployment_target  # [osx]
  - vs2022  # [win]
c_compiler_version:
  - 15               # [linux]
  - 21               # [osx]
cxx_compiler_version:
  - 15                 # [linux]
  - 21                 # [osx]
c_stdlib_version:  # [osx]
  - "11.0"         # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "11.0"                 # [osx]
