python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
c_compiler:  # [win]
  - vs2022   # [win]
cxx_compiler:  # [win]
  - vs2022     # [win]
target_platform:  # [win]
  - win-64        # [win]
c_compiler_version:  # [osx]
  - 19               # [osx]
cxx_compiler_version:  # [osx]
  - 19                 # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "13.5"                 # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "13.5"                 # [osx and x86_64]
