python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
  - 3.14
c_stdlib:
  - sysroot  # [linux]
  - macosx_deployment_target  # [osx]
c_compiler_version:
  - 14               # [linux]
  - 19               # [osx]
cxx_compiler_version:
  - 14                 # [linux]
  - 19                 # [osx]
c_stdlib_version:  # [osx]
  - "11.0"         # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "11.0"                 # [osx]
