{% set name = "pyarts" %}
{% set version = "3.0.0dev6" %}
{% set dev_url = "https://github.com/atmtools/arts" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: {{ dev_url }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a19de62763d761fd8d41a6e89fee87deafdface681b4b06401ec67092ebd78da
  # git_url: {{ dev_url }}.git
  # git_rev: bump-version
  # git_depth: 1

build:
  number: 1

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - cmake >=3.20
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - python {{ python }}
    - boost
    - docutils
    - eigen
    - fftw
    - lark-parser
    - libgomp         # [linux]
    - llvm-openmp     # [osx]
    - matplotlib
    - nanobind
    - netcdf4
    - nomkl  # [linux]
    - numpy>=2
    - openblas=*=*openmp*  # [linux]
    - openblas             # [win]
    - pip
    - pytest
    - pytest-runner
    - python-build
    - requests
    - scipy
    - setuptools
    - tqdm
    - typing_extensions
    - xarray>=2024
    - zlib
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}  # [osx and x86_64]
    - python
    - fftw
    - lark-parser
    - libgomp         # [linux]
    - matplotlib
    - netcdf4
    - {{ pin_compatible('numpy', lower_bound='2.0', upper_bound='3.0') }}
    - libopenblas=*=*openmp*  # [linux]
    - libopenblas             # [win]
    - requests
    - scipy
    - tqdm
    - typing_extensions
    - xarray>=2024
    - zlib


about:
  home: https://github.com/atmtools/arts
  summary: 'The Atmospheric Radiative Transfer Simulator'
  description: |
      Python interface to ARTS
  # License abbr. according to https://spdx.org/licenses/
  license: GPL-3.0-or-later
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file:
    - LICENSE.txt
    - vendor-licenses/
  # The doc_url and dev_url are optional.
  doc_url: https://atmtools.github.io/arts-docs-master/
  dev_url: https://github.com/atmtools/arts

extra:
  recipe-maintainers:
    - olemke
