{% set name = "pyarts" %}
{% set version = "2.5.11git0" %}
{% set dev_url = "https://github.com/atmtools/arts" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: {{ dev_url }}/archive/refs/tags/v{{ version }}.tar.gz
  #sha256: 19a70d978a8ac0b77d6248584ddaa50067597f4c3ee85fd71ef0dad8a76a89f8
  git_url: {{ dev_url }}.git
  git_depth: 1

build:
  skip: True  # [win]
  number: 1

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.20
    - make                               # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  host:
    - python {{ python }}
    - build
    - docutils
    - glew
    - glfw
    - lark-parser
    - libgomp         # [linux]
    - libopenblas     # [linux]
    - libmicrohttpd
    - llvm-openmp     # [osx]
    - matplotlib
    - netcdf4
    - pip
    - pytest
    - pytest-runner
    - scipy
    - xarray
    - zlib
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}  # [osx and x86_64]
    - python
    - glew
    - glfw
    - libmicrohttpd
    - matplotlib
    - netcdf4
    - {{ pin_compatible('numpy', lower_bound='1.22', upper_bound='3.0') }}
    - scipy
    - xarray
    - zlib


about:
  home: https://github.com/atmtools/arts
  summary: 'The Atmospheric Radiative Transfer Simulator'
  description: |
      Python interface to ARTS
  # License abbr. according to https://spdx.org/licenses/
  license: GPL-3.0-or-later
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file:
    - LICENSE.txt
    - vendor-licenses/
  # The doc_url and dev_url are optional.
  doc_url: https://atmtools.github.io/arts-docs-master/
  dev_url: https://github.com/atmtools/arts

extra:
  recipe-maintainers:
    - olemke
