{% set name = "pyarts" %}
{% set version = "2.6.16" %}
{% set dev_url = "https://github.com/olemke/arts" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: {{ dev_url }}/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 511ea89ed24e95cceb74e473a29de5b0f922f47898987a767c6789078dcb803b
  git_url: {{ dev_url }}.git
  git_rev: arts26-bump-version

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.20
    - make                               # [unix]
  host:
    - python {{ python }}
    - docutils
    - glew
    - glfw
    - lark-parser
    - libgl-devel     # [linux]
    - libgomp         # [linux]
    - libmicrohttpd
    - llvm-openmp     # [osx]
    - matplotlib
    - nomkl  # [linux]
    - netcdf4
    - openblas=*=*openmp*  # [linux]
    - pip
    - pytest
    - pytest-runner
    - python-build
    - scipy
    - setuptools
    - xarray
    - zlib
  run:
    - python
    - glew
    - glfw
    - libmicrohttpd
    - libopenblas=*=*openmp*  # [linux]
    - matplotlib
    - netcdf4
    - {{ pin_compatible('numpy', lower_bound='1.22', upper_bound='3.0') }}
    - scipy
    - xarray
    - zlib


about:
  home: https://github.com/atmtools/arts
  summary: 'The Atmospheric Radiative Transfer Simulator'
  description: |
      Python interface to ARTS
  # License abbr. according to https://spdx.org/licenses/
  license: GPL-3.0-or-later
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file:
    - LICENSE.txt
    - vendor-licenses/
  # The doc_url and dev_url are optional.
  doc_url: https://atmtools.github.io/arts-docs-2.6/
  dev_url: https://github.com/atmtools/arts

extra:
  recipe-maintainers:
    - olemke
