context:
  name: pyarts3
  version: 3.0.0dev9
  git_url: https://github.com/atmtools/arts

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # url: {{ git_url }}/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 4f8d5efa6a222d61f8fedfb4332a71a68db6886c30f014b7bce3c31a1e15297e
  git: ${{ git_url }}.git
  # git_rev: bump-version

build:
  number: 0

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - if: linux
      then:
        - ${{ stdlib('c') }}
    - if: osx
      then:
        - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake >=3.20
    - ninja
  host:
    - python
    - docutils
    - eigen
    - fast_float
    - fftw
    - lark-parser
    - libboost-devel
    - if: linux
      then:
        - libgomp
        - nomkl
        - openblas * *openmp*
    - if: osx
      then:
        - llvm-openmp
    - if: win
      then:
        - openblas
    - matplotlib
    - nanobind=2.13
    - netcdf4
    - numpy>=2
    - pip
    - pytest
    - pytest-runner
    - python-build
    - requests
    - scipy
    - setuptools
    - tqdm
    - typing_extensions
    - xarray>=2024
    - zlib
  run:
    - python
    - fftw
    - lark-parser
    - if: linux
      then:
        - libgomp
        - libopenblas * *openmp*
    - if: win
      then:
        - libopenblas
    - matplotlib
    - ${{ pin_compatible('numpy', lower_bound='2.0', upper_bound='3.0') }}
    - requests
    - scipy
    - tqdm
    - typing_extensions
    - xarray>=2024
    - zlib


about:
  homepage: https://github.com/atmtools/arts
  summary: 'The Atmospheric Radiative Transfer Simulator'
  description: |
      Python interface to ARTS
  # License abbr. according to https://spdx.org/licenses/
  license: GPL-3.0-or-later
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file:
    - LICENSE.txt
    - vendor-licenses/
  # The doc_url and dev_url are optional.
  documentation: https://atmtools.github.io/arts-docs-master/
  repository: https://github.com/atmtools/arts

extra:
  recipe-maintainers:
    - olemke
