name: Build conda packages

on: [push, pull_request]

jobs:
  build:
    name: Build (py${{ matrix.pyversion }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2025-vs2026"]
        pyversion: ["3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
          activate-environment: pyarts-build
          environment-file: etc/environment-pyarts-build.yml
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - shell: bash -l {0}
        run: rattler-build build --variant python=${{ matrix.pyversion }} -r pyarts
      - uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: pyarts3-conda-package-${{ matrix.os }}-py${{ matrix.pyversion }}
          path: output/**/pyarts3-*.conda
      - uses: actions/upload-artifact@v4
        if: runner.os == 'macOS'
        with:
          name: pyarts3-conda-package-${{ matrix.os }}-py${{ matrix.pyversion }}
          path: output/**/pyarts3-*.conda
      - uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: pyarts3-conda-package-${{ matrix.os }}-py${{ matrix.pyversion }}
          path: output/**/pyarts3-*.conda
  merge:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Merge Artifacts
          uses: actions/upload-artifact/merge@v4
          with:
            name: pyarts3-conda-packages
            retention-days: 7
            delete-merged: true
